// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// vec
arma::colvec vec(List a);
RcppExport SEXP _modeLLtest_vec(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(vec(a));
    return rcpp_result_gen;
END_RCPP
}
// cvll_mr
List cvll_mr(arma::dmat& x, arma::dmat& y, int n_row);
RcppExport SEXP _modeLLtest_cvll_mr(SEXP xSEXP, SEXP ySEXP, SEXP n_rowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::dmat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::dmat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_row(n_rowSEXP);
    rcpp_result_gen = Rcpp::wrap(cvll_mr(x, y, n_row));
    return rcpp_result_gen;
END_RCPP
}
// cvll_ols
List cvll_ols(arma::dmat& x, arma::mat& y, int n_row, int n_col);
RcppExport SEXP _modeLLtest_cvll_ols(SEXP xSEXP, SEXP ySEXP, SEXP n_rowSEXP, SEXP n_colSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::dmat& >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type n_row(n_rowSEXP);
    Rcpp::traits::input_parameter< int >::type n_col(n_colSEXP);
    rcpp_result_gen = Rcpp::wrap(cvll_ols(x, y, n_row, n_col));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_modeLLtest_vec", (DL_FUNC) &_modeLLtest_vec, 1},
    {"_modeLLtest_cvll_mr", (DL_FUNC) &_modeLLtest_cvll_mr, 3},
    {"_modeLLtest_cvll_ols", (DL_FUNC) &_modeLLtest_cvll_ols, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_modeLLtest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
