# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vec <- function(a) {
    .Call('_modeLLtest_vec', PACKAGE = 'modeLLtest', a)
}

cvll_mr <- function(x, y, n_row) {
    .Call('_modeLLtest_cvll_mr', PACKAGE = 'modeLLtest', x, y, n_row)
}

cvll_ols <- function(x, y, n_row, n_col) {
    .Call('_modeLLtest_cvll_ols', PACKAGE = 'modeLLtest', x, y, n_row, n_col)
}

